name: Create Preview Build

on:
  push:
    branches: ["preview"]

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: preview

  get_android_build:
    name: Find compatible Android preview build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: preview

  get_ios_build:
    name: Find compatible iOS preview build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: preview

  build_android:
    name: Build Android preview
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: preview

  build_ios:
    name: Build iOS preview
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: preview

  publish_preview_update:
    name: Publish preview update
    type: update
    environment: preview
    params:
      channel: preview
      message: ${{ github.commit_message }}
