#!/usr/bin/env bun
/**
 * Regenerates `docs/inventory.md`: one list of every shared component, hook and
 * helper, with the exact import path to use.
 *
 * The point is to make "does this already exist?" a single file read instead of
 * four directory listings, for humans and agents alike. Run it after adding or
 * removing anything in packages/ui or packages/mobile-ui; CI checks it is current.
 *
 *   bun run inventory           write docs/inventory.md
 *   bun run inventory --check   exit 1 if the file is stale (what CI runs)
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Source = {
  /** Directory to scan, relative to the repo root. */
  dir: string;
  /** How a consumer imports from this directory. */
  importPath: (basename: string) => string;
  heading: string;
  note?: string;
};

type Group = {
  package: string;
  blurb: string;
  sources: Source[];
};

const GROUPS: Group[] = [
  {
    package: "@ludika/mobile-ui",
    blurb: "Expo / React Native. HeroUI Native + Uniwind. Used by ludika-client and ludika-driver.",
    sources: [
      {
        dir: "packages/mobile-ui/src/components",
        heading: "Components",
        importPath: () => `@ludika/mobile-ui`,
        note: "Import from the package root. Subpath imports also work: `@ludika/mobile-ui/components/<file>`.",
      },
      {
        dir: "packages/mobile-ui/src/theme",
        heading: "Theme",
        importPath: () => `@ludika/mobile-ui`,
      },
      {
        dir: "packages/mobile-ui/src/lib",
        heading: "Helpers",
        importPath: (basename) => `@ludika/mobile-ui/lib/${basename}`,
      },
    ],
  },
  {
    package: "@ludika/ui",
    blurb: "Next.js / web. shadcn + Base UI + Tailwind v4. Used by apps/web.",
    sources: [
      {
        dir: "packages/ui/src/components",
        heading: "Components",
        importPath: (basename) => `@ludika/ui/components/${basename}`,
      },
      {
        dir: "packages/ui/src/hooks",
        heading: "Hooks",
        importPath: (basename) => `@ludika/ui/hooks/${basename}`,
      },
      {
        dir: "packages/ui/src/lib",
        heading: "Helpers",
        importPath: (basename) => `@ludika/ui/lib/${basename}`,
      },
    ],
  },
];

/** Directories whose contents are candidates for promotion, not shared API. */
const APP_LOCAL_DIRS = [
  "apps/ludika-client/components",
  "apps/ludika-driver/components",
  "apps/web/src/components",
];

const EXPORT_PATTERNS = [
  /^export\s+(?:async\s+)?function\s+([A-Za-z0-9_$]+)/gm,
  /^export\s+(?:const|let|class)\s+([A-Za-z0-9_$]+)/gm,
  /^export\s+(?:type|interface)\s+([A-Za-z0-9_$]+)/gm,
];

function exportedSymbols(source: string): string[] {
  const names = new Set<string>();

  for (const pattern of EXPORT_PATTERNS) {
    for (const match of source.matchAll(pattern)) {
      if (match[1]) names.add(match[1]);
    }
  }

  // `export { A, B as C, type D }`
  for (const match of source.matchAll(/^export\s*\{([^}]+)\}/gm)) {
    for (const part of match[1]!.split(",")) {
      const name = part
        .trim()
        .replace(/^type\s+/, "")
        .split(/\s+as\s+/)
        .pop()
        ?.trim();
      if (name) names.add(name);
    }
  }

  return [...names].sort((a, b) => a.localeCompare(b));
}

function sourceFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((entry) => /\.tsx?$/.test(entry) && !entry.endsWith(".d.ts") && entry !== "index.ts")
    .sort();
}

function renderTable(dir: string, source: Source): string[] {
  const files = sourceFiles(dir);
  if (files.length === 0) return [];

  const lines = [`#### ${source.heading}`, ""];
  if (source.note) lines.push(source.note, "");
  lines.push("| Exports | File | Import from |", "| --- | --- | --- |");

  for (const file of files) {
    const basename = file.replace(/\.tsx?$/, "");
    const symbols = exportedSymbols(readFileSync(join(dir, file), "utf8"));
    const rendered = symbols.length > 0 ? symbols.map((s) => `\`${s}\``).join(", ") : "-";
    lines.push(`| ${rendered} | \`${file}\` | \`${source.importPath(basename)}\` |`);
  }

  lines.push("");
  return lines;
}

function build(): string {
  const lines = [
    "# Shared code inventory",
    "",
    "**Generated by `bun run inventory`. Do not edit by hand.**",
    "",
    "Read this before creating a component. If something here fits, use it; if it",
    "nearly fits, extend it in its package rather than copying it into an app.",
    "",
  ];

  for (const group of GROUPS) {
    lines.push(`## ${group.package}`, "", group.blurb, "");
    for (const source of group.sources) {
      lines.push(...renderTable(source.dir, source));
    }
  }

  lines.push(
    "## App-local components",
    "",
    "Not shared API. Anything here that a second app would want belongs in a",
    "package instead - see the promotion rule in `AGENTS.md`.",
    "",
  );

  for (const dir of APP_LOCAL_DIRS) {
    const files = sourceFiles(dir);
    if (files.length === 0) continue;
    lines.push(`- \`${dir}/\`: ${files.map((file) => `\`${file}\``).join(", ")}`);
  }

  lines.push("");
  return lines.join("\n");
}

const target = "docs/inventory.md";
const generated = build();

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== generated) {
    console.error(`${target} is out of date. Run: bun run inventory`);
    process.exit(1);
  }
  console.log(`${target} is up to date.`);
} else {
  writeFileSync(target, generated);
  console.log(`Wrote ${target}`);
}
